-- Pickups configurations: HealthPickup, Coin, Key, Bomb, DNAStrand

return {
   Pickup = {
      HealthPickup = {
         entity_type = "HealthPickup",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "health",
         width = 16,
         height = 16,
         sprite_index = 37,
         hitbox = {w = 12, h = 12, ox = 2, oy = 2},
         shadow_width = 11,
         recovery_amount = 5,
      },
      Coin = {
         entity_type = "Coin",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "coin",
         width = 16,
         height = 16,
         sprite_index = 40,
         hitbox_width = 12,
         hitbox_height = 12,
         hitbox_offset_x = 2,
         hitbox_offset_y = 2,
         shadow_offset_y = 3,
         shadow_width = 11,
         amount = 1,
      },
      Key = {
         entity_type = "Key",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "key",
         width = 16,
         height = 16,
         sprite_index = 39,
         hitbox_width = 12,
         hitbox_height = 12,
         hitbox_offset_x = 2,
         hitbox_offset_y = 2,
         shadow_offset_y = 3,
         shadow_width = 11,
         amount = 1,
      },
      Bomb = {
         entity_type = "Bomb",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "bomb",
         width = 16,
         height = 16,
         sprite_index = 38,
         hitbox_width = 12,
         hitbox_height = 12,
         hitbox_offset_x = 2,
         hitbox_offset_y = 2,
         shadow_offset_y = 3,
         shadow_width = 11,
         amount = 1,
      },
      DNAStrand = {
         entity_type = "DNAStrand",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "xp",
         width = 16,
         height = 16,
         sprite_index = 41, -- DNA helix icon
         hitbox_width = 8,
         hitbox_height = 16,
         hitbox_offset_x = 4,
         hitbox_offset_y = 0,
         shadow_offset_y = 3,
         shadow_width = 11,
         -- xp_amount set at spawn time via instance_data
      },
      Mutation = {
         entity_type = "Mutation",
         tags = "pickup,collidable,drawable,sprite,background,shadow",
         pickup_effect = "mutation", -- Matches logic in pickup_handlers.lua
         width = 16,
         height = 16,
         sprite_index = 58, -- Placeholder, will be overridden by mutation_sprite
         hitbox_width = 12,
         hitbox_height = 12,
         hitbox_offset_x = 2,
         hitbox_offset_y = 2,
         shadow_offset_y = 3,
         shadow_width = 11,
         -- mutation field set via instance_data
      },
   }
}
